### ISSUE TITLE
Compatibility issues

### ISSUE THREAD

**Issue by TensorFu** [victor141516/httpcanary-magisk#6] opened 2023-10-08 10:50 UTC
Hello! I need your help.

I have encountered a compatibility issue, my Magisk shows, "Compatibility issue exists, this module is not loaded."

My Magisk version is 26.1
My device is: Xiaomi 10 Pro
My system is: MIUI 13 (Android 12)
![img_v2_8e58d076-cf9e-453e-b118-6d320883244g](https://github.com/victor141516/httpcanary-magisk/assets/41941359/ea2750c3-7952-4d4b-a313-b96caa14f90e)

The phrase in the image "存在兼容性问题，此模块未加载" means: There are compatibility issues, this module has not been loaded.

I used https://github.com/victor141516/httpcanary-magisk/raw/master/install.zip
This file v3.0. Not v1.0

v1.0 nomral
           
------
This is a log
[magisk_log_2023-10-08T21.34.28.log](https://github.com/victor141516/httpcanary-magisk/files/12840804/magisk_log_2023-10-08T21.34.28.log)

**Comment by victor141516** [comment] 2023-10-08 13:42
Hey! Thanks for the report!
I don't know why Magisk displays that error, but the module works anyway. Look this is my phone right now
![Screenshot_20231008_153649](https://github.com/victor141516/httpcanary-magisk/assets/5548950/4edaedbe-123c-4da6-b733-43a2450a21d0)

Since the last update of this module, you'll see the error, but the module should work. When I was working on the update I also thought that the module was not working, and I spent hours trying to figure out what was happening, only to find out that HttpCanary was working all the time.

Please just try to use the app and comment if it's not working so we can further investigate what's happening

**Comment by TensorFu** [comment] 2023-10-08 15:02
> Hey! Thanks for the report! I don't know why Magisk displays that error, but the module works anyway. Look this is my phone right now ![Screenshot_20231008_153649](https://user-images.githubusercontent.com/5548950/273451919-4edaedbe-123c-4da6-b733-43a2450a21d0.jpg)
> 
> Since the last update of this module, you'll see the error, but the module should work. When I was working on the update I also thought that the module was not working, and I spent hours trying to figure out what was happening, only to find out that HttpCanary was working all the time.
> 
> Please just try to use the app and comment if it's not working so we can further investigate what's happening


oh!!Thank you!
But
My phone has already rebooted, but my Magisk module is not working
![img_v2_0372cb13-93ba-4266-8f5d-8a9f63d6632g](https://github.com/victor141516/httpcanary-magisk/assets/41941359/1aa3a3b6-ad8e-4088-8ee4-50c4cd7026a2)

**Comment by TensorFu** [comment] 2023-10-08 15:05
Oh!!!Thank you!!!

**Comment by TensorFu** [comment] 2023-10-08 15:06
Oh!!!Thank you!!!
But
My phone has already rebooted and I have already granted it root permissions in Magisk., but my Magisk module is not working.

![img_v2_0372cb13-93ba-4266-8f5d-8a9f63d6632g](https://github.com/victor141516/httpcanary-magisk/assets/41941359/ed2241fc-4c99-49e9-b6ba-7a0018f81b91)

**Comment by victor141516** [comment] 2023-10-09 12:08
Did you accept the dialogs that are displayed when you install the module? those install all the needed certificates as a user.

If so, can you please install the module again and post an screenshot of the installation log? Like this:

![Screenshot_20231009_140658 (1)](https://github.com/victor141516/httpcanary-magisk/assets/5548950/fb130fc3-888f-4f79-a537-d3ed241bc6e5)

**Comment by TensorFu** [comment] 2023-10-10 06:50
I'm here    
Look at this    
Thank you again for your patience.

![img_v2_44afdfa1-5b0f-4cf6-b928-710c52cb22ag](https://github.com/victor141516/httpcanary-magisk/assets/41941359/003dd17a-546d-4c42-9976-fbb720f1be97)
![img_v2_87d2d996-26eb-40d5-8120-8a63d7ff6beg](https://github.com/victor141516/httpcanary-magisk/assets/41941359/1cc8dd07-7ade-4578-9057-0ea894b38d3a)

After I installed this magisk module.
It shows "Choose a certificate type."
"VPN&app user certificate"
"WI-FI certificate"
I chose "VPN&app user certificate", and I rebooted my phone.

**Comment by victor141516** [comment] 2023-10-10 10:04
Have you tried using the app? I also have that error on the HttpCanary app that you posted, but then the app works fine.

It it's indeed not working, then we can continue troubleshooting:
Yes you have to choose VPN&app, and then you're prompted with another dialog that asks for the certificate name. In this case you have to just tap on Accept (the name is `HttpCanary`

Next thing is check if the certificate is correctly mounted on /system. For this you'll need adb or a root file explorer. The file is in `/system/etc/security/cacerts/87bc3517.0`. You can check that using adb with:
`adb shell ls -la /system/etc/security/cacerts/87bc3517.0`

Also check that the file contains the certificate data:
`adb shell head -1 /system/etc/security/cacerts/87bc3517.0`
It should print this:
`-----BEGIN CERTIFICATE-----`

If the file is there and contains that text, then the certificate is installed correctly and the problem is other thing.

**Comment by TensorFu** [comment] 2023-10-11 02:35
<img width="977" alt="image" src="https://github.com/victor141516/httpcanary-magisk/assets/41941359/7d191b01-17c3-4b5a-bb8c-a385242c7a63">


Yes, it seems the error is elsewhere. Thank you very much for your patient response.

**Comment by victor141516** [comment] 2023-10-11 09:35
I don't know what can be the issue here :(
Can I somehow help you?

**Comment by TensorFu** [comment] 2023-10-12 01:52
Your Magisk is very powerful. Everything is normal, and after the modules are correctly installed, no further modifications are needed, ignore all errors.

Because at this point, HttpCanary is already able to work normally.

Thank you again for your help, wishing you all the best.

**Comment by victor141516** [comment] 2023-10-12 10:07
Thank you for your kind words!

I'm closing the issue as completed 👍

**Closed as completed by victor141516** 2023-10-12 10:07 UTC
